### PR TITLE
Fix name change detection, allow FastLogin to respect AuthMe registration limits

### LINKED ISSUE #423: Premium username change -> few "problems".
**Hi!**

**I use FastLogin with AdvancedLogin.**
FastLogin config: https://pastebin.com/QU3bn52S
AdvancedLogin (not very useful...): https://pastebin.com/29PUh85j

It's quite new on my server, as I began to have more and more players, and wanted something better for the players that changed their username. My server runs on OnlineMode=false.

One of my players changed his username from Jobeee to mvjik. AdvancedLogin saw that, did the change, and handles him as a "cracked"... didn't really understood why. So now when we parse %fastlogin_status% on him it returns "Unknown".

So he has to enter his passcode, and second issue, he is still considerated as Jobeee....?..... I don't know what I did wrong, but I did. When he write on the chat it is Jobeee, when we look on the Dynmap it is jobeee, but if we want to change permission (LuckPerms) then it is mvjik!....

Hope you will be able to help me. Thanks

### PR DESCRIPTION
**Pull request by Kamilkime**
### Summary of your change
First change fixes name change detection on PaperSpigot. Because the gameprofile didn't have the skin set and the server is set to offline-mode - Paper was using a cached profile from usercache.json, which had the old username. That way the name change was spotted, but basically ignored by Paper.

Second change allows to respect the per IP registration limit of AuthMe. Due to the limitations of its API - some reflections have to be used. When registering using the API - a different type of registration is triggered. The API one doesn't check for IP limits. The reflection allows FastLogin to trigger a registration like it would be done using the `/register` command - that way the limits will be checked.

Also because AuthMe makes the registration async - there's no good way to detect if the registration was successful, FastLogin will always display a message about auto-register and then AuthMe will send a message about IP limit. I've changed the default auto-register message to at least a bit account for possible registration fail.

### Related issue
Fixes #423, #437, #457, #458

### CODE REVIEW

**Comment by games647** [comment]
>Also because AuthMe makes the registration async - there's no good way to detect if the registration was successful, FastLogin will always display a message about auto-register and then AuthMe will send a message about IP limit. I've changed the default auto-register message to at least a bit account for possible registration fail.

Yeah it's a little bit sad, almost all auth plugins do not expose an thread-safe API which is also returns the success status. There are many work-arounds.

File: bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hook/AuthMeHook.java [hunk 1]
```diff
@@ -41,25 +58,32 @@ public void onSessionRestore(RestoreSessionEvent restoreSessionEvent) {
...
-        return true;
+        //if we have the management - we can trigger register with IP limit checks
+        if (authmeManagement != null) {
+            authmeManagement.performRegister(RegistrationMethod.PASSWORD_REGISTRATION,
+                    ApiPasswordRegisterParams.of(player, password, true));
+        } else {
+            authmeAPI.forceRegister(player, password);
+        }
+
+        return authmeAPI.isRegistered(player.getName());
```
Comment (games647) [inline bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hook/AuthMeHook.java:87]: Couldn't this cause an race-condition? If the calls are async, they would immediately return and therefore the check `authmeAPI.isRegistered` could return false even though the registration will be successful. 

This has to be tested with async enabled AuthMe.

File: core/src/main/resources/config.yml [hunk 2]
```diff
@@ -36,6 +36,15 @@ anti-bot:
 # For more information: https://github.com/games647/FastLogin#why-do-players-have-to-invoke-a-command
 autoRegister: false
 
+# Should FastLogin respect per IP limit of registrations (e.g. in AuthMe)
+# Because most auth plugins do their stuff async - FastLogin will still think the player was registered
+# To work best - you also need to enable auto-register-unknown
```
Comment (games647) [inline core/src/main/resources/config.yml:41]: `auto-register-unknown` You meant `auto-register`?

File: bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hook/AuthMeHook.java (hunk 1 above)
Comment (Kamilkime) [reply bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hook/AuthMeHook.java]: Yeah, I forgot to change that back to true - checking if isRegistered() sometimes works and sometime doesn't

File: core/src/main/resources/config.yml (hunk 2 above)
Comment (Kamilkime) [reply core/src/main/resources/config.yml:41]: Nope, I meant `auto-register-unknown` - that way FastLogin will try to register the player again, so the player would get the message about the IP limit again. If `auto-register-unknown` is set to false - they would only get that message the first time they join and they might not see it immediately

If `auto-register` is set to false - the IP limit would just not be used by FastLogin, because it wouldn't register the player at all

**Review by games647 — APPROVED** [review]

**Comment by games647** [comment]
Thank you very much.

**Comment by Fargus5** [comment]
Thank you for working on it.
Hope that a solution will be update soon.
Thanks to both for what you are doing for all of us

**Comment by elmaslarry** [comment]
Me gustaría saber si se arreglo el bypass con los registros de ip en authme con la ultima version? No quiero dejar que los jugadores puedan bypassear ese limite de registros por IP 

Si finalmente se arreglo, debo cambiar algo en mi configuracion? o simplemente reemplazar el -jar
Gracias

**Comment by elmaslarry** [comment]
I would like to know if the bypass with the ip registers in authme with the latest version was fixed? I don't want to let players bypass that IP record limit

If it is finally fixed, should I change something in my configuration? or just replace the -jar
Thank you

**Comment by Kamilkime** [comment]
> I would like to know if the bypass with the ip registers in authme with the latest version was fixed? I don't want to let players bypass that IP record limit
> 
> If it is finally fixed, should I change something in my configuration? or just replace the -jar
> Thank you
> 

Yeah, you need to add a **respectIpLimit** section to your config.yml and set it's value to true. I'd also advice enabling **auto-register-unknown** for the best experience

**Comment by Fargus5** [comment]
@Kamilkime I saw that there was an exchange between you and the developer. the problem was solved or are you still working on it? I just ask you to know why no update has been released on spigot yet.
Sorry to bother you.

**Comment by Kamilkime** [comment]
> @Kamilkime I saw that there was an exchange between you and the developer. the problem was solved or are you still working on it? I just ask you to know why no update has been released on spigot yet.
> Sorry to bother you.

The issue was fixed - but there just aren't any official releases on spigotmc. To get the newest version with the fixes - you need to get it from https://ci.codemc.org/job/Games647/job/FastLogin/changes

**Comment by Fargus5** [comment]
thanks

**Comment by elmaslarry** [comment]
So i need to put: 

respectIpLimit: true

autoRegister: true 


¿?

**Comment by Kamilkime** [comment]
> So i need to put: 
> 
> respectIpLimit: true
> 
> autoRegister: true 
> 
> 
> ¿?
> 
> 

Yup, and it would be best to also enable auto-register-unknown

**Comment by elmaslarry** [comment]
Okey thanks!

**Comment by elmaslarry** [comment]
I need to add some new message ¿? in lang file ?

**Comment by Kamilkime** [comment]
> I need to add some new message ¿? in lang file ?

Nope, the messages are all the same as before
